---
title: "data_manipulation"
author: "Courtney Johnson"
date: "September 20, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
options(tibble.print_min = 3)

litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```

## name the columns to keep

```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)
```

## keep range of columns

```{r}
select(litters_data, group:gd_of_birth)
```

## remove pups_survive column

```{r}
select(litters_data, -pups_survive)
```

## rename variables

```{r}
select(litters_data, GROUP = group, litter_number, gest_data_0_weight = gd0_weight)
rename(litters_data, gest_day_0_weight = gd0_weight)
```

## use select helpers:

```{r}
select(litters_data, starts_with("gd"))
select(litters_data, litter_number, starts_with("pup"))

select(litters_data, litter_number, everything())
```

## filter observations

```{r}
filter(litters_data, gd0_weight < 25)
filter(litters_data, gd0_weight >= 25)

filter(litters_data, pups_born_alive == 8)

filter(litters_data, !is.na(gd0_weight))

filter(litters_data, group == "Low8" | group == "Low7")
filter(litters_data, group %in% c("Low7", "Low8"))

filter(litters_data, pups_born_alive %in% 4:6)

filter(litters_data, pups_born_alive %in% 4:7, !is.na(gd0_weight))
```

## Filter learning assessment

```{r}
filter(pups_data, sex == 1)
filter(pups_data, pd_walk < 11, sex == 2)
```

## Mutate

Create variables

```{r}
mutate(litters_data,
  wt_gain = gd18_weight - gd0_weight,
  group = tolower(group)
)

mutate(litters_data,
       wt_gain = gd18_weight - gd0_weight,
       wt_gain_squared = wt_gain^2)
```



